---
title: "OddsRatio"
author: "Joe Vargovich"
date: "2022-12-13"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(rcompanion)
#Confidence Scales
#Unconfident, Not confident (can manage, but difficult), Average, Confident, Very Confident (fluent)
#Top row Control, bottom row treament

#No values for Unconfident and Very Confident in each group
#Counts: Control: 2 Not confident, 4 average, 0 confident (first 3, no extreme vals so far.)
#Treatment: 3 Not confident, 3 average, 2 confident (second 3, no extreme vals so far.)

#Pre survey data.
confMatrix <- matrix(c(0,4,5,1,0,1,7,3,1,0), nrow = 2);
cramerV(confMatrix)
```
```{r}
#2024 Control 0 confident, 6 not  confident/average
# 2024 Treatment 2 confident, 6 not confident/avg
#confidentMatrix <- matrix(c(0, 6, 2, 6), nrow = 2);
#cramerV(confidentMatrix)
#That is the old data ^

#2024 new data

```
```{r}
chisq.test(confMatrix)
```
```{r}
#Fisher is used for smaller sample size to determine stat difference between groups
fisher.test(confMatrix)
```




```{r}
#create 2x3 table?????????????? 3/5 not sure what this is doing.
data = matrix(c(6, 9, 8, 5, 12, 9), nrow = 2)

#view dataset
data

cramerV(data)
```

